CREATE TABLE events (
INT ID PRIMARY KEY,
DAY TEXT NOT NULL,
MONTH TEXT NOT NULL,
YEAR TEXT NOT NULL,
group_id INT NOT NULL
);
CREATE TABLE calendar (
INT ID PRIMARY KEY,
EVENT_NAME TEXT NOT NULL,
GROUP_ID INTEGER NOT NULL,
FOREIGN KEY (GROUP_ID)
REFERENCES events (group_id)
);
