INSERT into CALENDAR (EVENT_NAME, GROUP_ID)
VALUES ('HARIDAASA VAIBHAVA', 1);

INSERT into EVENTS (DAY, MONTH, YEAR, GROUP_ID)
VALUES ('28', 'MARCH', '2020', 1)

INSERT into EVENTS (DAY, MONTH, YEAR, GROUP_ID)
VALUES ('20', 'JANUARY', '2020', 2);


INSERT into CALENDAR (EVENT_NAME, GROUP_ID)
VALUES ('NADAVIPANCHI', 3);

INSERT into EVENTS (DAY, MONTH, YEAR, GROUP_ID)
VALUES ('5', 'MARCH', '2020', 3); 